# Generated by Django 3.1 on 2020-08-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
