# Generated by Django 3.1 on 2020-08-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0002_auto_20200828_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customization',
            new_name='customizable',
        ),
    ]
