# Generated by Django 3.1 on 2020-08-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0003_auto_20200829_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
