# Generated by Django 3.1 on 2020-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0004_order_number_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hamper_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
