# Generated by Django 3.1 on 2020-09-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0005_order_hamper_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='state',
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
