# Generated by Django 3.1 on 2020-09-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0014_auto_20200920_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryDetail',
            new_name='DeliveryDetails',
        ),
        migrations.AlterModelOptions(
            name='deliverydetails',
            options={'verbose_name_plural': 'Delivery Details'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
    ]
