# Generated by Django 3.1 on 2020-09-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0015_auto_20200920_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
