# Generated by Django 3.1 on 2020-09-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0017_auto_20200920_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
