# Generated by Django 3.1 on 2020-09-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalisay_main', '0018_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='date_added',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='date_ordered',
        ),
    ]
